channels:
  - conda-forge
  - defaults

dependencies:
  - fenics=2019.1.0
  - git
  - intervaltree=3.1.0
  - matplotlib
  - mshr=2019.1.0
  - pip
  - pytest
  - pythonocc-core=7.9.0
  - pyyaml=6.0.2
  - pip:
    - shapely=2.1.1
    - triangle=20230923
    - windIO=2.1.1

variables:
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple
