channels:
  - conda-forge
  - defaults

dependencies:
  - intervaltree
  - matplotlib
  - openmdao
  - palettable
  - pint
  - pip
  - pytest
  - pythonocc-core
  - pyyaml
  - pre-commit
  - shapely
  - windIO
  - pip:
    - triangle

variables:
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple
