name: CI_SONATA

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.os }} Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    defaults:
        run:
            shell: bash -l {0}


    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-14, macos-latest]
        python-version: ["3.9"]#, "3.10", "3.11"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Set CONDA_SUBDIR for macOS
        if: matrix.os == 'macos-14'
        run: echo "CONDA_SUBDIR=osx-64" >> $GITHUB_ENV

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        # https://github.com/marketplace/actions/setup-miniconda
        with:
          miniconda-version: "latest"
          channels: conda-forge
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yaml
          activate-environment: test
          auto-activate-base: false
          
      - name: Download and install anba
        run: |
          git clone https://github.com/ANBA4/anba4.git
          cd anba4
          pip install -e .

      - name: Install SONATA
        run: |
          pip install -e .

#       - name: Install dependencies
#         shell: bash -l {0}
#         run: |
#           conda activate test
#           conda install --force-reinstall mpi4py openmpi
#           conda list | grep mpi  # Debugging step to check MPI versions

      - name: Run example 0
        run: |
          cd examples/0_beams
          export MPLBACKEND=Agg
          python 0_SONATA_init_box_beam_HT_antisym_layup_15_6_SI_SmithChopra91.py
      
      - name: Run pytest
        run: |
          python -m pytest -v --disable-warnings

      - name: Run example 1
        run: |
          cd examples/1_IEA15MW
          export MPLBACKEND=Agg
          python 1_sonata_IEA15.py
      
      - name: Run example 2
        run: |
          cd examples/2_IEA22MW
          export MPLBACKEND=Agg
          python 2_sonata_IEA22.py
      
      - name: Run example 5
        run: |
          cd examples/5_IEA_5MW
          export MPLBACKEND=Agg
          python 5_sonata_IEA5.py

      - name: Run example 6
        run: |
          cd examples/6_beam_stress
          export MPLBACKEND=Agg
          python 6_sonata_beam_stress.py

